
const reservedTokens = {
    keywords: [
        "socho",
        "likho",
        "pucho",
        "agar",
        "fir",
        "warna",
        "jabtak",
        "chalao",
        "ruko",
        "async",
        "await",
        "function",
    ],
    operators: [
        "+",
        "plus",
        "-",
        "minus",
        "*",
        "times",
        "/",
        "divided_by",
        "%",
        "modulus",
        "mod",
        "=",
        "equals",
        "!=",
        "not_equals",
        ">",
        "<",
        ">=",
        "<=",
        "&&",
        "AND",
        "||",
        "OR",
        "!",
        "NOT",
        "++",
        "increase",
        "--",
        "decrease",
        "true",
        "sehi",
        "false",
        "galat",
    ],
    brackets: [
        "(",
        ")",
        "{",
        "}",
        "[",
        "]",
    ],
    endOfStatement: ";",
}

export default reservedTokens;